apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    version: v1
  name: api-vs
spec:
  gateways:
  - api-gateway
  hosts:
  - "*.com"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: python-api-svc
        port:
          number: 80
        subset: v1
