apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
  labels:
    version: v1
  name: api-gateway
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - "api.resources.cloud"
    - "*.ap-south-1.vpce.amazonaws.com"
    port:
      name: http-dev
      number: 80
      protocol: HTTP