apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  labels:
    version: v1
  name: api-vs
spec:
  gateways:
  - api-gateway
  hosts:
  - "api.resources.cloud"
  - "*.ap-south-1.vpce.amazonaws.com"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: python-api-svc.apps.svc.cluster.local
        port:
          number: 80
